# Generated by Django 3.2.7 on 2021-09-23 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='slug',
            field=models.SlugField(default=1, verbose_name='URL'),
            preserve_default=False,
        ),
    ]
